name: Docker Snapshot Release

on:
  workflow_dispatch:

jobs:
  apiary-docker-image:
    name: Apiary Docker Image Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure Apiary Docker Image Builds.
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/expediagroup/apiary-metastore-core:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          