name: Docker Snapshot Release

on:
  workflow_dispatch:

jobs:
  apiary-docker-image:
    name: Apiary Docker Image Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ensure Apiary Docker Image Builds.
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: "Dockerfile"
          always_pull: true
          tag_with_sha: true
          repository: expediagroup/apiary-waggledance
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          push: true